CREATE TABLE [dbo].[Claims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(100) NOT NULL, 
    [Value] VARCHAR(MAX) NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [RoleId] UNIQUEIDENTIFIER NOT NULL,
    [AllowedOn] DATETIME NOT NULL,
    [ExpiresOn] DATETIME NOT NULL,
    [SYS_CREATE_DATE] DATETIME NOT NULL, 
    [SYS_CREATE_USER_ID] VARCHAR(150) NOT NULL, 
    [SYS_MODIFY_DATE] DATETIME NOT NULL, 
    [SYS_MODIFY_USER_ID] VARCHAR(150) NOT NULL, 
    CONSTRAINT [FK_Claims_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]), 
    CONSTRAINT [FK_Claims_Roles] FOREIGN KEY ([RoleId]) REFERENCES [Roles]([Id])
)
