CREATE TABLE [dbo].[Recruiters] (
    [Id]   UNIQUEIDENTIFIER NOT NULL,
    [Name] VARCHAR (MAX) NOT NULL,
    [SYS_STATUS] VARCHAR(5) NOT NULL,
    [SYS_CREATE_DATE] DATETIME  NOT NULL,
    [SYS_CREATE_USER_ID] VARCHAR(100) NOT NULL,
    [SYS_MODIFY_DATE] DATETIME  NOT NULL,
    [SYS_MODIFY_USER_ID] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_Recruiters] PRIMARY KEY CLUSTERED ([Id] ASC)
);

