CREATE TABLE [dbo].[RoleClaims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[RoleId] UNIQUEIDENTIFIER NOT NULL,
	[ClaimType] VARCHAR(MAX) NOT NULL,
	[ClaimValue] VARCHAR(MAX) NOT NULL,
    [SYS_CREATE_DATE] DATETIME  NOT NULL,
    [SYS_CREATE_USER_ID] VARCHAR(100) NOT NULL,
    [SYS_MODIFY_DATE] DATETIME  NOT NULL,
    [SYS_MODIFY_USER_ID] VARCHAR(100) NOT NULL,
    CONSTRAINT [FK_RoleClaims_Users] FOREIGN KEY ([RoleId]) REFERENCES [Roles]([Id])
)
