CREATE TABLE [dbo].[TokenHistory]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Token] VARCHAR(MAX) NOT NULL,
	[RefreshToken] VARCHAR(MAX) NOT NULL,
	[SignatureKey] VARCHAR(MAX) NOT NULL,
	[AllowedOn] DATETIME NOT NULL,
	[ExpiresOn] DATETIME NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[SYS_CREATE_DATE] DATETIME NOT NULL,
	[SYS_CREATE_USER_ID] VARCHAR(150) NOT NULL,
	[SYS_MODIFY_DATE] DATETIME NOT NULL,
	[SYS_MODIFY_USER_ID] VARCHAR(150) NOT NULL, 
    CONSTRAINT [FK_TokenHistory_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
