CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Photo] VARCHAR(MAX) NOT NULL,
    [FirstName] VARCHAR(150) NOT NULL, 
    [LastName] VARCHAR(150) NOT NULL, 
    [Username] VARCHAR(150) NOT NULL, 
    [Email] VARCHAR(320) UNIQUE NOT NULL, 
    [Phone] VARCHAR(15) NULL,
    [HashedPassword] VARCHAR(MAX) NOT NULL, 
    [SYS_STATUS] VARCHAR(5) NULL,
    [SYS_CREATE_DATE] DATETIME NOT NULL,
    [SYS_CREATE_USER_ID] DATETIME NOT NULL,
    [SYS_MODIFY_DATE] DATETIME NOT NULL,
    [SYS_MODIFY_USER_ID] VARCHAR(150) NOT NULL
)
