CREATE TABLE [dbo].[Users_Roles]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[RoleId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[SYS_STATUS] VARCHAR(5) NOT NULL,
	[SYS_CREATE_DATE] DATETIME NOT NULL,
	[SYS_CREATE_USER_ID] VARCHAR(150) NOT NULL,
	[SYS_MODIFY_DATE] DATETIME NOT NULL,
	[SYS_MODIFY_USER_ID] VARCHAR(150) NOT NULL
)
