CREATE TABLE [dbo].[UserLogins]
(
	[LoginProvider] VARCHAR(128) NOT NULL,
	[ProviderKey] VARCHAR(128) NOT NULL,
	[ProviderDisplayName] VARCHAR(MAX) NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
    [SYS_CREATE_DATE] DATETIME  NOT NULL,
    [SYS_CREATE_USER_ID] VARCHAR(100) NOT NULL,
    [SYS_MODIFY_DATE] DATETIME  NOT NULL,
    [SYS_MODIFY_USER_ID] VARCHAR(100) NOT NULL, 
    PRIMARY KEY ([LoginProvider], [ProviderKey]),
    CONSTRAINT [FK_UserLogins_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
